/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Ahmad Nur Latif P
 */
public class menu_utama extends javax.swing.JFrame {

    /**
     * Creates new form menu_utama
     */
    public menu_utama() {
        initComponents();
        String teknisi = UserID.getNamaTeknisi();
        label_selamatdatang.setText("Hallo, "+teknisi);
        tampilkanTanggal_hariini();
        tampilalamatService();
        tampilkanWaktuSekarang();
        waktuBerjalan();
    }
    

    private void tampilkanTanggal_hariini() {
        Date tanggalSaatIni = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("EEEE,dd-MM-yyyy");
        String tanggalFormatted = formatter.format(tanggalSaatIni);
        tanggal_label.setText(tanggalFormatted);
    }

    private void tampilkanWaktuSekarang() {
        Date waktuSaatIni = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");
        String waktuFormatted = formatter.format(waktuSaatIni);
        jam_label.setText(waktuFormatted);
    }

    private void waktuBerjalan() {
        int delay = 1000;
        Timer waktu = new Timer(delay, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tampilkanWaktuSekarang();
            }
        });
        waktu.start();
    }

    private void tampilalamatService() {
        String teksAlamatPanjang = "Jl. Raya Tengah No.80, RT.6/RW.1, Gedong, Kec. Ps.Rebo, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13760, Indonesia";
        alamat_label.setText("<html><p style=' text-align: center;'>" + teksAlamatPanjang + "</p></html>");
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_selamatdatang = new javax.swing.JLabel();
        tanggal_label = new javax.swing.JLabel();
        jam_label = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        alamat_label = new javax.swing.JLabel();
        rep_teknisi = new javax.swing.JMenuBar();
        master = new javax.swing.JMenu();
        menu_teknisi = new javax.swing.JMenuItem();
        menu_pelanggan = new javax.swing.JMenuItem();
        menu_sparepart = new javax.swing.JMenuItem();
        menu_aksesoris = new javax.swing.JMenuItem();
        menu_service = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        menu_pembayaran = new javax.swing.JMenuItem();
        report = new javax.swing.JMenu();
        menu_rteknisi = new javax.swing.JMenuItem();
        menu_rpelanggan = new javax.swing.JMenuItem();
        menu_rsparepart = new javax.swing.JMenuItem();
        menu_raksesoris = new javax.swing.JMenuItem();
        menu_rservice = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        riwayat_transaksi = new javax.swing.JMenuItem();
        keluar = new javax.swing.JMenu();
        menu_keluarakun = new javax.swing.JMenuItem();
        menu_keluarapk = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("version 1.0 made by kelompok 1");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 0, 0, new java.awt.Color(255, 255, 255)));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/menu_logo_1.png"))); // NOI18N

        label_selamatdatang.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        label_selamatdatang.setForeground(new java.awt.Color(255, 255, 255));
        label_selamatdatang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_selamatdatang.setText("HALLO");

        tanggal_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tanggal_label.setForeground(new java.awt.Color(255, 255, 255));
        tanggal_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tanggal_label.setText("Tanggal Hari Ini");

        jam_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jam_label.setForeground(new java.awt.Color(255, 255, 255));
        jam_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jam_label.setText("Jam Hari Ini");

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        alamat_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        alamat_label.setForeground(new java.awt.Color(255, 255, 255));
        alamat_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alamat_label.setText("TEKS ALAMAT GADGET HOUSE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_selamatdatang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tanggal_label, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jam_label, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamat_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggal_label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jam_label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_selamatdatang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alamat_label, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rep_teknisi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rep_teknisi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rep_teknisi.setName(""); // NOI18N
        rep_teknisi.setPreferredSize(new java.awt.Dimension(344, 35));

        master.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/teknisi.png"))); // NOI18N
        master.setText("Master |");
        master.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        master.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        master.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        menu_teknisi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_teknisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/teknisi.png"))); // NOI18N
        menu_teknisi.setText("Teknisi");
        menu_teknisi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_teknisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_teknisiActionPerformed(evt);
            }
        });
        master.add(menu_teknisi);

        menu_pelanggan.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_pelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pelanggan.png"))); // NOI18N
        menu_pelanggan.setText("Pelanggan");
        menu_pelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pelangganActionPerformed(evt);
            }
        });
        master.add(menu_pelanggan);

        menu_sparepart.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_sparepart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sparepart.png"))); // NOI18N
        menu_sparepart.setText("Sparepart");
        menu_sparepart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_sparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_sparepartActionPerformed(evt);
            }
        });
        master.add(menu_sparepart);

        menu_aksesoris.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_aksesoris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/aksesoris.png"))); // NOI18N
        menu_aksesoris.setText("Aksesoris");
        menu_aksesoris.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_aksesoris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_aksesorisActionPerformed(evt);
            }
        });
        master.add(menu_aksesoris);

        menu_service.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_service.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/service.png"))); // NOI18N
        menu_service.setText("Service");
        menu_service.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_serviceActionPerformed(evt);
            }
        });
        master.add(menu_service);

        rep_teknisi.add(master);

        transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/transaction.png"))); // NOI18N
        transaksi.setText("Transaksi |");
        transaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transaksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menu_pembayaran.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_pembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/transaction.png"))); // NOI18N
        menu_pembayaran.setText("Pembayaran");
        menu_pembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pembayaranActionPerformed(evt);
            }
        });
        transaksi.add(menu_pembayaran);

        rep_teknisi.add(transaksi);

        report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        report.setText("Report |");
        report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        report.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menu_rteknisi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_rteknisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        menu_rteknisi.setText("Data Teknisi");
        menu_rteknisi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_rteknisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_rteknisiActionPerformed(evt);
            }
        });
        report.add(menu_rteknisi);

        menu_rpelanggan.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_rpelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        menu_rpelanggan.setText("Data Pelanggan");
        menu_rpelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_rpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_rpelangganActionPerformed(evt);
            }
        });
        report.add(menu_rpelanggan);

        menu_rsparepart.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_rsparepart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        menu_rsparepart.setText("Data Sparepart");
        menu_rsparepart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_rsparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_rsparepartActionPerformed(evt);
            }
        });
        report.add(menu_rsparepart);

        menu_raksesoris.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_raksesoris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        menu_raksesoris.setText("Data Aksesoris");
        menu_raksesoris.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_raksesoris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_raksesorisActionPerformed(evt);
            }
        });
        report.add(menu_raksesoris);

        menu_rservice.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_rservice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        menu_rservice.setText("Data Service");
        menu_rservice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_rservice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_rserviceActionPerformed(evt);
            }
        });
        report.add(menu_rservice);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        jMenuItem1.setText("Data Penjualan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        report.add(jMenuItem1);

        riwayat_transaksi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        riwayat_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        riwayat_transaksi.setText("Data Riwayat Transaksi");
        riwayat_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayat_transaksiActionPerformed(evt);
            }
        });
        report.add(riwayat_transaksi);

        rep_teknisi.add(report);

        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/exit.png"))); // NOI18N
        keluar.setText("Keluar |");
        keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        menu_keluarakun.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_keluarakun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/login.png"))); // NOI18N
        menu_keluarakun.setText("Keluar Akun");
        menu_keluarakun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_keluarakun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_keluarakunActionPerformed(evt);
            }
        });
        keluar.add(menu_keluarakun);

        menu_keluarapk.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        menu_keluarapk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/exit.png"))); // NOI18N
        menu_keluarapk.setText("Keluar Aplikasi");
        menu_keluarapk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_keluarapk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_keluarapkActionPerformed(evt);
            }
        });
        keluar.add(menu_keluarapk);

        rep_teknisi.add(keluar);

        setJMenuBar(rep_teknisi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed

    }//GEN-LAST:event_keluarActionPerformed

    private void menu_keluarakunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_keluarakunActionPerformed
        this.dispose();
        login keluarakun = new login();
        keluarakun.setVisible(true);
        keluarakun.setLocationRelativeTo(null);    // TODO add your handling code here:
    }//GEN-LAST:event_menu_keluarakunActionPerformed

    private void menu_rteknisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_rteknisiActionPerformed
        form_report.report_teknisi rk = new form_report.report_teknisi();
        rk.setVisible(true);
        rk.setLocationRelativeTo(null); 
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_rteknisiActionPerformed

    private void menu_teknisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_teknisiActionPerformed
        master_teknisi mt = new master_teknisi();
        mt.setVisible(true);
        mt.setLocationRelativeTo(null);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menu_teknisiActionPerformed

    private void menu_keluarapkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_keluarapkActionPerformed
        int konfirmasi_keluarapp = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
        if (konfirmasi_keluarapp == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menu_keluarapkActionPerformed

    private void menu_raksesorisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_raksesorisActionPerformed
        form_report.report_aksesoris rak = new form_report.report_aksesoris();
        rak.setVisible(true);
        rak.setLocationRelativeTo(null);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menu_raksesorisActionPerformed

    private void menu_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pelangganActionPerformed
        master_pelanggan mp = new master_pelanggan();
        mp.setVisible(true);
        mp.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_menu_pelangganActionPerformed

    private void menu_sparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sparepartActionPerformed
        master_sparepart ms = new master_sparepart();
        ms.setVisible(true);
        ms.setLocationRelativeTo(null);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menu_sparepartActionPerformed

    private void menu_aksesorisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_aksesorisActionPerformed
        master_aksesoris ma = new master_aksesoris();
        ma.setVisible(true);
        ma.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_menu_aksesorisActionPerformed

    private void menu_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_serviceActionPerformed
        master_service mser = new master_service();
        mser.setVisible(true);
        mser.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_menu_serviceActionPerformed

    private void menu_rpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_rpelangganActionPerformed
        form_report.report_pelanggan rp = new form_report.report_pelanggan();
        rp.setVisible(true);
        rp.setLocationRelativeTo(null);
    }//GEN-LAST:event_menu_rpelangganActionPerformed

    private void menu_rsparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_rsparepartActionPerformed
        form_report.report_sparepart rs = new form_report.report_sparepart();
        rs.setVisible(true);
        rs.setLocationRelativeTo(null);
    }//GEN-LAST:event_menu_rsparepartActionPerformed

    private void menu_rserviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_rserviceActionPerformed
        form_report.report_service rser = new form_report.report_service();
        rser.setVisible(true);
        rser.setLocationRelativeTo(null);
    }//GEN-LAST:event_menu_rserviceActionPerformed

    private void menu_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pembayaranActionPerformed
        transaksi_pembayaran tp = new transaksi_pembayaran();
        tp.setVisible(true);
        tp.setLocationRelativeTo(null);
    }//GEN-LAST:event_menu_pembayaranActionPerformed

    private void riwayat_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayat_transaksiActionPerformed
        form_report.riwayat_transaksi rt = new form_report.riwayat_transaksi();
        rt.setVisible(true);
        rt.setLocationRelativeTo(null);
    }//GEN-LAST:event_riwayat_transaksiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        form_report.report_penjualan rt = new form_report.report_penjualan();
        rt.setVisible(true);
        rt.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utama().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat_label;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jam_label;
    private javax.swing.JMenu keluar;
    private javax.swing.JLabel label_selamatdatang;
    private javax.swing.JMenu master;
    private javax.swing.JMenuItem menu_aksesoris;
    private javax.swing.JMenuItem menu_keluarakun;
    private javax.swing.JMenuItem menu_keluarapk;
    private javax.swing.JMenuItem menu_pelanggan;
    private javax.swing.JMenuItem menu_pembayaran;
    private javax.swing.JMenuItem menu_raksesoris;
    private javax.swing.JMenuItem menu_rpelanggan;
    private javax.swing.JMenuItem menu_rservice;
    private javax.swing.JMenuItem menu_rsparepart;
    private javax.swing.JMenuItem menu_rteknisi;
    private javax.swing.JMenuItem menu_service;
    private javax.swing.JMenuItem menu_sparepart;
    private javax.swing.JMenuItem menu_teknisi;
    private javax.swing.JMenuBar rep_teknisi;
    private javax.swing.JMenu report;
    private javax.swing.JMenuItem riwayat_transaksi;
    private javax.swing.JLabel tanggal_label;
    private javax.swing.JMenu transaksi;
    // End of variables declaration//GEN-END:variables
}
